import { KPIMetrics, SecurityEventItem, TrafficPoint, ThreatCategoryStat, QuantumJobDetails } from '@/types';

export const DEMO_KPI_METRICS: KPIMetrics = {
  threatsDetected: 6374,
  threatsGrowth: '+1.30%',
  accessibleNetworksError: '0.35%',
  eventsAnalyzed: 400,
  anomalyRate: '0.75%',
  modelConfidence: 99.65,
  quantumVerificationRate: 98.4,
};

export const DEMO_TRAFFIC_TIMELINE: TrafficPoint[] = [
  { time: '04:00', traffic: 700, baseline: 650 },
  { time: '08:00', traffic: 1200, baseline: 1100 },
  { time: '10:00', traffic: 850, baseline: 800, anomalyFlag: true, anomalyValue: '1,274', anomalyLabel: 'Direct networks' },
  { time: '12:00', traffic: 2450, baseline: 1300, anomalyFlag: true, anomalyValue: '5,670', anomalyLabel: 'Anomaly detected' },
  { time: '14:00', traffic: 1400, baseline: 1250 },
  { time: '16:00', traffic: 950, baseline: 900 },
  { time: '18:00', traffic: 2100, baseline: 1000, anomalyFlag: true, anomalyValue: '2,100', anomalyLabel: 'Burst traffic' },
  { time: '20:00', traffic: 1300, baseline: 950 },
  { time: '22:00', traffic: 1950, baseline: 800 },
];

export const DEMO_SECURITY_EVENTS: SecurityEventItem[] = [
  // Exact Reference Image Events
  {
    id: 'EVT-001',
    username: 'sec_admin_01',
    targetService: 'Auth SSO Portal',
    category: 'Failed Login',
    status: 'high-risk',
    timestamp: '10:22 AM',
    riskScore: 92,
    quantumFidelity: 0.982,
    classicalConfidence: 0.94,
    ipAddress: '203.0.113.24',
    location: 'Singapore, SG',
    mitigationAction: 'Blocked at identity edge firewall',
  },
  {
    id: 'EVT-002',
    username: 'analyst_ext',
    targetService: 'VPN Gateway Beta',
    category: 'Unusual Location',
    status: 'suspicious',
    timestamp: '10:18 AM',
    riskScore: 67,
    quantumFidelity: 0.965,
    classicalConfidence: 0.72,
    ipAddress: '198.51.100.89',
    location: 'Sao Paulo, BR',
    mitigationAction: 'Verify via biometric step-up authentication',
  },
  {
    id: 'EVT-003',
    username: 'operator_dev_7',
    targetService: 'Kubernetes API',
    category: 'Device Change',
    status: 'suspicious',
    timestamp: '10:15 AM',
    riskScore: 45,
    quantumFidelity: 0.978,
    classicalConfidence: 0.81,
    ipAddress: '192.0.2.14',
    location: 'Dublin, IE',
    mitigationAction: 'Quantum state verification circuit executed',
  },
  {
    id: 'EVT-004',
    username: 'bot_net_scan',
    targetService: 'External Microservice',
    category: 'Unfamiliar IP',
    status: 'high-risk',
    timestamp: '10:12 AM',
    riskScore: 88,
    quantumFidelity: 0.989,
    classicalConfidence: 0.91,
    ipAddress: '185.190.21.4',
    location: 'Unknown Proxy',
    mitigationAction: 'Blocked by automated perimeter defense rule',
  },
  // Existing Telemetry Records Tested by E2E Audit
  {
    id: '5028000066559',
    username: 'ext_gw_probe',
    targetService: 'API Gateway Ingress',
    category: 'Quantum Anomaly Probe',
    status: 'high-risk',
    timestamp: '08-01-2026 15:56',
    riskScore: 89,
    quantumFidelity: 0.971,
    classicalConfidence: 0.74,
    ipAddress: '185.220.101.5',
    location: 'Tor Exit Node #14',
    mitigationAction: 'Quarantined by Q-SHIELD kernel firewall',
  },
  {
    id: '5008006050308',
    username: 'anom_tunnel_9x',
    targetService: 'Core Microservices',
    category: 'Suspicious Tunnel',
    status: 'suspicious',
    timestamp: '08-01-2026 14:10',
    riskScore: 68,
    quantumFidelity: 0.952,
    classicalConfidence: 0.62,
    ipAddress: '91.240.118.23',
    location: 'Unknown Subnet',
    mitigationAction: 'Rate-limited; quantum circuit validation triggered',
  },
  {
    id: '2023082115737',
    username: 'sec_agent_04',
    targetService: 'Auth Gate Alpha',
    category: 'Safe connections',
    status: 'safe',
    timestamp: '08-01-2026 16:47',
    riskScore: 12,
    quantumFidelity: 0.994,
    classicalConfidence: 0.985,
    ipAddress: '192.168.10.42',
    location: 'Frankfurt, DE',
    mitigationAction: 'Passed automated multi-factor handshake',
  },
  {
    id: '202500000601',
    username: 'infra_svc_vault',
    targetService: 'Key Management DB',
    category: 'Safe connections',
    status: 'safe',
    timestamp: '08-01-2026 16:17',
    riskScore: 18,
    quantumFidelity: 0.988,
    classicalConfidence: 0.972,
    ipAddress: '10.200.4.15',
    location: 'Internal Pod C',
    mitigationAction: 'Session token refreshed with post-quantum signature',
  },
  {
    id: '5023009650501',
    username: 'analyst_corp_02',
    targetService: 'Telemetry Stream',
    category: 'Safe connections',
    status: 'safe',
    timestamp: '08-01-2026 14:48',
    riskScore: 8,
    quantumFidelity: 0.999,
    classicalConfidence: 0.991,
    ipAddress: '172.16.88.90',
    location: 'Zurich, CH',
    mitigationAction: 'Normal encrypted stream verified',
  },
  {
    id: '5055704866532',
    username: 'cluster_node_08',
    targetService: 'Qiskit Simulator Pod',
    category: 'Safe connections',
    status: 'safe',
    timestamp: '08-01-2026 13:22',
    riskScore: 5,
    quantumFidelity: 0.998,
    classicalConfidence: 0.989,
    ipAddress: '10.150.12.8',
    location: 'Local Cluster',
    mitigationAction: 'Standard state vector checkpoint',
  },
  {
    id: '5065656656532',
    username: 'darknet_bot_harvest',
    targetService: 'Public Edge CDN',
    category: 'Exfiltration Burst',
    status: 'high-risk',
    timestamp: '08-01-2026 12:45',
    riskScore: 94,
    quantumFidelity: 0.966,
    classicalConfidence: 0.81,
    ipAddress: '45.154.255.89',
    location: 'St. Petersburg, RU',
    mitigationAction: 'Traffic dropped at edge; zero-trust policy applied',
  },
];

export const DEMO_THREAT_CATEGORIES: ThreatCategoryStat[] = [
  { name: 'Quantum Tunnel Anomaly', count: 48, percentage: 42, riskLevel: 'high' },
  { name: 'Encrypted Credential Stuffing', count: 32, percentage: 28, riskLevel: 'high' },
  { name: 'Reconnaissance Scans', count: 21, percentage: 18, riskLevel: 'medium' },
  { name: 'API Parameter Tampering', count: 14, percentage: 12, riskLevel: 'low' },
];

export const DEMO_MONTHLY_BARS = [
  { month: 'Apr', normal: 40, anomaly: 12 },
  { month: 'May', normal: 65, anomaly: 28 },
  { month: 'Jun', normal: 55, anomaly: 18 },
  { month: 'Jul', normal: 85, anomaly: 45 },
  { month: 'Aug', normal: 45, anomaly: 20 },
  { month: 'Sep', normal: 75, anomaly: 35 },
  { month: 'Oct', normal: 90, anomaly: 22 },
];

export const DEMO_QUANTUM_JOB: QuantumJobDetails = {
  jobId: 'q-job-ibm-79402c-falcon',
  status: 'COMPLETED',
  backend: 'ibm_kyiv (127-qubit Eagle r3)',
  qubitCount: 8,
  circuitDepth: 36,
  quantumKernel: 'ZZFeatureMap(entanglement=full, reps=2)',
  stateFidelity: 0.9842,
  classicalModelScore: 0.732,
  quantumModelScore: 0.958,
  quantumConfidenceGain: '+22.6%',
  finalDecision: 'ANOMALY_CONFIRMED',
  executionTimeMs: 412,
};
